### ISSUE TITLE
Missing "WCH-Link" driver causing connection issues with the board.

### ISSUE THREAD

**Issue by nenemoan** [vsdip/vsdsquadron_pio#1]
When trying to upload your code to the VSDSquadron Mini, most devices show an error.
This happens due to a missing WCH-Link driver which shows up in your device manager as an unknown device or "other".

https://github.com/Community-PIO-CH32V/wchlink-driver-windows

1. Download this driver and unzip it.
2. Go to your device manager and locate the unknown driver, right click on it and select update driver
3. Select 'browse my computer for drivers', select the unzipped folder and install it.

The installed driver should show up under 'interface'.
Try uploading the code again...
The problem should be solved! :)

**Comment by yathAg** [comment]
Hey @nenemoan Thank you for pointing this out!! Could you make a pull request with these steps mentioned in the readme? Make sure to include any screenshots if required. This would allow you to be a contributor, and we look forward to more such insights!

**Comment by yathAg** [comment]
Also, a fun experiment would be to include the package in the `platform.json` file. This allows PIO to install packages on setup. See the original file [here](https://github.com/Community-PIO-CH32V/platform-ch32v/blob/develop/platform.json) for ideas. Try this on your end, and if it works out, include it in the pull request.

**Comment by tejasbg19** [comment]
From past two days I was able to program VSD mini by installing the necessary Drivers. But today when I tried to upload code, I got an Error stating "WLink Open Error". So, I tried to install the drivers again, but was unable to Install the driver through "Update Driver" in Device Management.
