### ISSUE TITLE
Information related to PA1,PA2 of mini board

### ISSUE THREAD

**Issue by yashgupta17402** [vsdip/vsdsquadron_pio#10]
Can you share some resources about using analog pins of sensors and PA1 of vsdsquadron mini board.I could not find any code or project regarding these pins.

**Comment by vsdip** [comment]
did you check this?
https://github.com/openwch/ch32v003/tree/main/EVT/EXAM/ADC

**Comment by yashgupta17402** [comment]
thankyou Sir it worked for us.
