### ISSUE TITLE
OpenCV bindings and OV7670 Support Library for VSD Squadron Mini

### ISSUE THREAD

**Issue by dhanvantibhavsar** [vsdip/vsdsquadron_pio#11]
Hello, 
I am trying to implement low-bit quantized neural network on VSD Squadron Mini, 
I am able to implement predictions on the board, but facing issues with capturing images using arduino supported OV7670 and preprocessing the data on the board itself using OpenCV.

Please update if there are bindings present for OpenCV, and libraries for OV7670 available, or if there are any alternatives available. please update here on this issue

**Comment by yathAg** [comment]
Can you share any sample project related to what you are trying to do?

You might have to adapt the drivers for the camera and once you complete that, what is the preprocessing you want to do?

**Comment by dhanvantibhavsar** [comment]
https://github.com/dhanvantibhavsar/RiscV/tree/main/BitNetMCU/VsdSquadron/Arduino_Ov7670
you can check this repo of mine, where I am capturing images using OV7670, as of now which is interfaced with arduino, it provides 160x120 images, I will then have to convert them to 16x16 images and then use it for further processing, was thinking of using opencv to carry out image processing, was also thinking to use some basic image processing algos to attain better detection

**Comment by yathAg** [comment]
I'd suggest developing the camera interface on the VsdsquadronMini and try to write algorithms that compress the images. 

It might not be possible to run openCV on the Mini (i might be wrong)

You might have to write your own compression algorithm and that itself is amazing progress!
