### ISSUE TITLE
providing external clock in the mini board 

### ISSUE THREAD

**Issue by SiddharthVikram068** [vsdip/vsdsquadron_pio#13]
this issue addresses the concern on how to use an external clock in the vsd squadron mini board.

**Comment by yathAg** [comment]
What is the application that you would be using and frequency that you are targeting?

**Comment by SiddharthVikram068** [comment]
> What is the application that you would be using and frequency that you are targeting?

our application is a fire alarm based on a gas sensor and a buzzer, we wanna introduce clock glitches using an external clock and perform data corruption and instruction skips. We are okay with any frequency that the vsd can operate upon, the lower the better. We are using an esp32 to provide the external clock

**Comment by yathAg** [comment]
Just from a brief look at the data sheet, refer to the clock tree and section 10.4.1(boot and clock) you will have to provide a variable clock on the oscillator pins. 

You can read up about VCXO's, i will read up more and share details soon

So an approach would be to remove the crystal on pin PA1 and PA2 and connect your own circuit there.

**Comment by SiddharthVikram068** [comment]
it will be a very risky approach if we try to remove the in built crystal oscillator to use our own circuit, since we might need the crystal oscillator again for some other applications. 

The reference manual does offer some insight into using an external clock for TIM1 interface. If you can share any details on how to configure the code to allow an external clock would be very helpful, thank you

**Comment by yathAg** [comment]
Removing Y1 ( it's pretty easy with a hot air gun) is the only solution that comes to mind.

Once you successfully remove that, then you can connect the ESP or any other clock source to PA1. 

![Screenshot_20240610_191815_GitHub.jpg](https://github.com/vsdip/vsdsquadron_pio/assets/58807660/5d07eaa5-8ba4-4585-adb8-0089c33beb4f)

Whenever you don't want to use that, use the internal oscillator `HSI.`

There are specific bits you can use to switch as described in the screenshot from the reference manual.



You cannot run the board from a timer. The timer is generated using the internal clock `HSI` or external clock `HSE (Connected to PA1)`
