### ISSUE TITLE
"Query: Can we Write Values into Microcontroller Registers via Debugger"

### ISSUE THREAD

**Issue by Sreyas-J** [vsdip/vsdsquadron_pio#14]
I would like to know if there is a feature that allows users to write values directly into the registers of the microcontroller using the debugger. Currently, it appears that the debugger provides read-only access to register values. Enabling write access would greatly enhance debugging capabilities and streamline the development process.

**Comment by yathAg** [comment]
Hi, which registers are you trying to write into? 

Usually, the contents must be written in your code if there are any configuration registers ( for example, SPI registers).

Please provide some more details, and I will try to give a solution.
