### ISSUE TITLE
Ubuntu OS (solved issue 4 and was working just fine untill encountering problem in the terminal like in issue 7)

### ISSUE THREAD

**Issue by ARX-0** [vsdip/vsdsquadron_pio#15]
![Screenshot from 2024-06-12 21-47-50](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/6b95575e-4450-4468-83c2-013c502f0580)

![Screenshot from 2024-06-12 21-48-57](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/64632217-9b29-47eb-9f91-451ba9e0faa9)

had solved the previous issue (issue 4)[https://github.com/vsdip/vsdsquadron_pio/issues/4]
faced this problem sometime after having good work done and having good uploads.I was able to upload (before this problem showed up

**Comment by yathAg** [comment]
Hi, Can you check if the USB device is connected using `lsusb`

If not, try restarting your system and reconnecting the USB.

**Comment by yathAg** [comment]
@ARX-0 did this work?

**Comment by ARX-0** [comment]
@yathAg 
![Screenshot from 2024-06-13 10-10-42](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/55523a1e-66bf-434e-b06c-6b0d03edcba5)

it detects the WinChipHead and yet it persists :(

**Comment by ARX-0** [comment]
How i did things earlier 

for downlioading the the platform io udev rules
```
curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules | sudo tee /etc/udev/rules.d/99-platformio-udev.rules

```
Opened the file for adding the additional rules 
```
sudo nano /etc/udev/rules.d/99-platformio-udev.rules
```
adding the additional rules at the end of the file 
```
SUBSYSTEM=="usb", ATTR{idVendor}=="1a86", ATTR{idProduct}=="8010", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="4348", ATTR{idProduct}=="55e0", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}=="1a86", ATTR{idProduct}=="8012", GROUP="plugdev"

```
saved the file and relloading for the rules to apply
```
sudo udevadm control --reload-rules
sudo udevadm trigger
```
i made shure that i was a part of the plugdev group 
sudo usermod -aG plugdev $USER

**Comment by ARX-0** [comment]
Commming to the actual issue here
 
 used the command ```lsusb```
 
![Screenshot from 2024-06-13 10-17-37](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/ef0ca8e4-3179-431b-98bf-8e702926e431)

it seems i have acess to all of the necessary WCH
"WinChipHead"

tried disconnecting and reconnecting the mini in different ports 
untill now i dont have a successful upload

**Comment by ARX-0** [comment]
switched to windows @yathAg thanks for the help 
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/5f397e62-23c5-47d5-9097-a99806635674)
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/9a7af54f-ba35-413e-983b-f4d1743fd53c)
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/39073a17-ab71-48b4-98b5-d748c04023e3)
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/9bb3c019-bc69-42e2-9c7e-4e9b9d5cb606)
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/d3932e5e-d618-49e4-b0bb-ea8a4c91f988)
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/a5e1d68c-d119-40e9-8837-0e6061adb699)

it dosnet work afer this 

solution by @yathAg 

![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/db019348-8395-4a31-a82b-c43267a91011)
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/a6379724-537e-4e14-a01b-c49512ddf88e)
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/daee93d2-fca8-4eaa-832e-0694e7e4fc71)
![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/c0804c0f-4e81-405f-a0ab-4bcb37ac4e7a)

after this disconnect, connect try again

**Comment by ARX-0** [comment]
it will upload :)
