### ISSUE TITLE
Resetting using PD7

### ISSUE THREAD

**Issue by swetha3456** [vsdip/vsdsquadron_pio#17]
@yathAg We need to reset the board using the PD7 pin but when we change the voltage the reset does not occur. Are there any changes we should make in the code for this to happen?

**Comment by yathAg** [comment]
Changing the voltage internally through the code on `PD7` is changing the gpio voltage and not issuing a reset. 

From reference manual section 3.2 

![image](https://github.com/vsdip/vsdsquadron_pio/assets/58807660/7d083a84-9dde-4c2e-a4bf-b0522b4ea320)

From datasheet

![image](https://github.com/vsdip/vsdsquadron_pio/assets/58807660/7262d3d5-17ba-4ea3-bdf0-758cc1daa221)


These documents are in the docs folder of this repository.

Depending on when you want to reset, you can
- Connect pd7 to a switch connected to the ground
- issue a software rest
- power cycle the board
- Use the other listed methods
