### ISSUE TITLE
serial monitor how to acess + aurdino libraries not supported 

### ISSUE THREAD

**Issue by ARX-0** [vsdip/vsdsquadron_pio#18]
i tried the serial monitot Clt+T and this is what i get 

![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/e75192d3-8212-4f9b-a47a-c1d5a47e2eb8)

i tried switching to aurdino IDE it seems that Onewire.h dosent include the risc_v lib in it to run the analogread() function 

![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/0da315be-186a-4e77-a685-eecbbd915bf7)

![image](https://github.com/vsdip/vsdsquadron_pio/assets/143102635/b8f0b0e2-535b-45d1-b427-444f30e5c4b5)

all i wanted was to read pH and temp sensor code and display it in the serial monitor,
talking to people they said that my HC-05 module dosnet header support for this board

**Comment by yathAg** [comment]
Could you let me know if you were able to display any test string successfully on the terminal? For example, `Hello World`?

If yes, then you would read data from the sensor, store it in a variable, and display it. 

As for libraries, you can read the datasheet, understand how the sensor works, and write the suitable functions from scratch.
