### ISSUE TITLE
Unable to Flash(Upload) example program to mini Squadron board in Ubuntu OS

### ISSUE THREAD

**Issue by anandr16910** [vsdip/vsdsquadron_pio#3]
Installed VScode.
Installed platform PIO extension; 

had few problems with python interpreter but I solved that. 

-   python PATH was missing(FIXED this: which Python3 and inserting this link location i.e **/usr/bin/Python3.XX)**

-   particular command is required to help sync Python VScode and platform PIO
     **sudo apt-get install python3.XX-venv**
so Platform PIO is installed successfully.
But now I am unable to upload the program to board in **Ubuntu OS**I
possible outcomes :

- checked with github  repositories based on CH32V003
     https://docs.platformio.org/en/latest/core/installation/udev-rules.html#platformio-udev-rules
    after clicking above this page opens and throws another link:
     https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules
     now here lies the problem i.e **_our board CH32V003 is not listed._**
- different try: tried to clone  this @https://github.com/Community-PIO-CH32V/platform-ch32v.git  under platform PIO of advanced installation of platform section.  Throws an Error 
![Screenshot from 2024-02-15 00-05-20](https://github.com/vsdip/vsdsquadron_pio/assets/77429504/420663db-b6cf-44f5-ade4-df4d0cfc5cd3)
- So unable to program the board in Linux environment.

**Comment by yathAg** [comment]
Duplicate issue, Find the solution at [issue#4](https://github.com/vsdip/vsdsquadron_pio/issues/4)
