### ISSUE TITLE
Unable to Flash(Upload) example program to mini Squadron board in Ubuntu OS

### ISSUE THREAD

**Issue by anandr16910** [vsdip/vsdsquadron_pio#4]
Installed VScode.
Installed platform PIO extension; 

had few problems with python interpreter but I solved that. 

-   python PATH was missing(FIXED this: which Python3 and inserting this link location i.e **/usr/bin/Python3.XX)**

-   particular command is required to help sync Python VScode and platform PIO
     **sudo apt-get install python3.XX-venv**
so Platform PIO is installed successfully.
But now I am unable to upload the program to board in **Ubuntu OS**I
possible outcomes :

- checked with github  repositories based on CH32V003
     https://docs.platformio.org/en/latest/core/installation/udev-rules.html#platformio-udev-rules
    after clicking above this page opens and throws another link:
     https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules
     now here lies the problem i.e **_our board CH32V003 is not listed._**
- different try: tried to clone  this @https://github.com/Community-PIO-CH32V/platform-ch32v.git  under platform PIO of advanced installation of platform section.  Throws an Error 
![Screenshot from 2024-02-15 00-05-20](https://github.com/vsdip/vsdsquadron_pio/assets/77429504/420663db-b6cf-44f5-ade4-df4d0cfc5cd3)
- So unable to program the board in Linux environment.
![failed_upload](https://github.com/vsdip/vsdsquadron_pio/assets/77429504/eefaab13-819a-47d2-afd9-03531c2109eb)
above is of FAILED message (unable to upload/burn/debug the code to board)

**Comment by yathAg** [comment]
Make sure you have the Udev rules file. It can be found at `/etc/udev/rules.d/99-platformio-udev.rules`

If it is not there, install using the following in the terminal.
```
curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules | sudo tee /etc/udev/rules.d/99-platformio-udev.rules
```

Then, append the following at the bottom of the file. ( you might require admin access)

```
SUBSYSTEM=="usb", ATTR{idVendor}="1a86", ATTR{idProduct}=="8010", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}="4348", ATTR{idProduct}=="55e0", GROUP="plugdev"
SUBSYSTEM=="usb", ATTR{idVendor}="1a86", ATTR{idProduct}=="8012", GROUP="plugdev"
```

- Restart VScode
- Disconnect and Reconnect the mini for UDev rules to apply.

This should fix the issue.

**Comment by yathAg** [comment]
If this works out, could you please document these steps and any other info in the `install.md` file? 

Thanks for the help!

**Comment by anandr16910** [comment]
> If this works out, could you please document these steps and any other info in the `install.md` file?
> 
> Thanks for the help!

Hi YathAg, I have already documented steps required to setup board in Ubuntu. After this I clicked on commit changes for install.md file.
Why my changes are not reflected whenever I click on install.md

**Comment by yathAg** [comment]
Since you are currently not a collaborator, and owner of the repository, you will have to make a pull request to include the changes. 

https://opensource.com/article/19/7/create-pull-request-github


Further a commit only saves changes to the local repository on your machine.
