### ISSUE TITLE
Firmware required for supporting Micropython in risc-5  Ch32V003 board.

### ISSUE THREAD

**Issue by anandr16910** [vsdip/vsdsquadron_pio#6]
There is no firmware found in list of supported Microcontrollers of Micropython/downloads website for this ch32v003.
Do I need to create firmware for this board.
List of supported list includes:
ESP32
CC3200.... and many more.

Ours is not listed.
Please help.

**Comment by yathAg** [comment]
I don't have experience with micropython. However, from a brief look at the documentation, it is not supported for any CH32 series of chips. You would have to develop the framework independently for such a use case.

All the best!

**Comment by anandr16910** [comment]
Yes thanks for reply. Even I got responses from other repositories i.e wch/ch32 which states that Micropython is not supported for ch32. But yes that's the truth and let's accept this for time being. I will close this topic here in this repository.
