### ISSUE TITLE
Unable to Install WCH-link

### ISSUE THREAD

**Issue by Supriya648** [vsdip/vsdsquadron_pio#7]
Unable to install WCH-link driver because I cant find the WCH-link driver under Interface or Other devices in Device Manager.
<img width="581" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/4a083bae-9f77-4c7b-a8e1-592fcb916ad5">
 Please help!

**Comment by yathAg** [comment]
Please try

[https://github.com/Community-PIO-CH32V/wchlink-driver-windows/archive/refs/heads/main.zip](https://github.com/Community-PIO-CH32V/wchlink-driver-windows/archive/refs/heads/main.zip)

If this does not work then

Download wchlinkUtilty from [https://www.wch.cn/downloads/WCH-LinkUtility_ZIP.html](https://www.wch.cn/downloads/WCH-LinkUtility_ZIP.html)

![image](https://github.com/vsdip/vsdsquadron_pio/assets/58807660/2e6c311f-ae03-43c6-9868-780d8f8c7072)

You should have a tool like this..let me know if it shows a WCHLInk connected there

**Comment by yathAg** [comment]
@Supriya648, for reference, when u click refresh, you should see `RISC-V Link[#1]` written. If not, please let me know.

**Comment by Supriya648** [comment]
Hi @yathAg, 

https://github.com/Community-PIO-CH32V/wchlink-driver-windows/archive/refs/heads/main.zip

This does not work for me.

I have Downloaded wchlinkUtilty and this is what I see.


<img width="439" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/e45c491a-a4b5-49c7-8d61-d1ae7d7bf5b7">


But i cant see it in my device manager.

<img width="326" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/eaf5a7b5-4708-489d-978e-be2581436843">

Unable to upload.
<img width="657" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/66fe2abf-9392-4948-94f8-2648f6d19a45">

**Comment by Supriya648** [comment]
After clicking on refresh in WCH-Linkutility

<img width="437" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/76bb46d7-3e9a-4efc-8600-0390f343dd69">

**Comment by Supriya648** [comment]
Hi @yathAg,
I found a folder named WCH.CN and installed the SETUP and now I am able to upload the code.
The WCH-Link error is resolved.

<img width="541" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/d8dc8d9f-c059-4de1-a735-b1b0fb285ea1">

 Previously when I tried installing I would get the below message.
<img width="586" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/e9cfc440-1693-431d-8009-69d8fc8b5a40">


After successfully installing the driver you will get the below dialog box.




<img width="548" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/f3402230-a090-409d-97b2-f197099c5b3e">




Now opened the WCH-Linkutility  click refresh, you should see RISC-V Link[#1] written as shown in the below image.

<p align="center">
<img width="244" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/eb84908c-125b-4f58-8b74-eb350f9f4538">
<p/>


<p align="center">
<img width="443" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/a692ec34-5671-42e9-a8cc-a3e335cff2a9">
<p/>

Now checked the device manger under "Interface" you will find "WCH-LinkRV"

<p align="center">
<img width="259" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/5fd8cb8c-0033-4073-82a9-365c1f639072">
<p/>

Successfully uploaded the code and the WCHLink error was rectified.

<p align="center">
<img width="673" alt="image" src="https://github.com/vsdip/vsdsquadron_pio/assets/61849924/71859b8d-5312-4652-a7e9-989b14ff0fc2">
<p/>

**Comment by AnoushkaTripathi** [comment]
![image](https://github.com/user-attachments/assets/e9bf6542-b762-4fae-a8fd-44ba43c123e5)
An update to this issue, If you are using mournriver ide
1. Install MRS Studio IDE not MRS community
2. If you get issue Unknown device for your board in device manager than update it with the path of IDE
